
[build.environment]
  # Replace with your actual backend URL
  API_URL = "https://back-end-misty-haze-3575.fly.dev"

[[redirects]]
  from = "/api/*"
  to = "https://back-end-misty-haze-3575.fly.dev/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}