
[build.environment]
  # Replace with your actual backend URL
  API_URL = "https://sattam-back-end.onrender.com"

[[redirects]]
  from = "/api/*"
  to = "https://sattam-back-end.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}