[build]
  publish = "/"
  command = ""  # No build command needed for a static site

[build.environment]
  API_URL = "https://your-backend-url.app"  # Replace with your actual backend URL

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200